# Generated by Django 5.2.5 on 2025-09-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0002_alter_donationcategory_options_donation_campaign_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='alt_mobile',
            new_name='mobile',
        ),
    ]
