# Generated by Django 5.2.5 on 2025-09-06 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0003_rename_alt_mobile_donation_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trust.donationcategory'),
        ),
    ]
