# Generated by Django 5.2.5 on 2025-09-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0004_campaign_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='category',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='category',
        ),
    ]
