# Generated by Django 5.2.5 on 2025-09-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0005_remove_campaign_category_remove_donation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
