# Generated by Django 5.2.5 on 2025-09-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0006_alter_donation_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
