# Generated by Django 5.2.5 on 2025-09-06 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0007_alter_donation_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trust.donationcategory'),
        ),
    ]
