# Generated by Django 5.2.5 on 2025-09-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0008_donation_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='impactcategory',
            options={'verbose_name_plural': 'Impact Categories'},
        ),
        migrations.AddField(
            model_name='latestnewsview',
            name='publisheddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
