# Generated by Django 5.2.5 on 2025-09-15 08:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0009_alter_aboutus_options_alter_impactcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnewsview',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
