# Generated by Django 5.2.5 on 2025-09-15 09:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0011_alter_aboutus_description_alter_topic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofwork',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
