# Generated by Django 5.2.5 on 2025-09-15 09:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0012_alter_areaofwork_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestnewsview',
            name='extra_image1',
        ),
        migrations.RemoveField(
            model_name='latestnewsview',
            name='extra_image2',
        ),
        migrations.RemoveField(
            model_name='latestnewsview',
            name='extra_image3',
        ),
        migrations.AlterField(
            model_name='latestnewsview',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
