# Generated by Django 5.2.5 on 2025-09-15 09:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0013_remove_latestnewsview_extra_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnewsview',
            name='extra_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/latestnews'),
        ),
        migrations.AddField(
            model_name='latestnewsview',
            name='extra_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/latestnews'),
        ),
        migrations.AddField(
            model_name='latestnewsview',
            name='extra_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/latestnews'),
        ),
        migrations.AlterField(
            model_name='latestnewsview',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
