# Generated by Django 5.2.5 on 2025-09-15 10:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0014_latestnewsview_extra_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactstory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trustee',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
