# Generated by Django 5.2.5 on 2025-09-20 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0016_district_domain_mandal_subdomain_village_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trust.domain'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
